### ISSUE TITLE
Please provide a demo :)

### ISSUE THREAD

**Issue by lastzero** [sebastian-raubach/frickl-web#8]

**Comment by sebastian-raubach** [comment]
I don't really have anywhere to host it.
Open to suggestions if there's any service that's free to use.
I better not link to my private copy 😁

**Comment by lastzero** [comment]
If it's only client side and only needs static server assets, you can use GitHub pages for free.

**Comment by sebastian-raubach** [comment]
There's a server side running Java and MySQL as well.

**Comment by lastzero** [comment]
I see, don't think you'll get Java hosting for free... cheapest solution would probably be a small DigitalOcean droplet or similar unless you find a way to mock the server API with static files.

**Comment by sebastian-raubach** [comment]
@lastzero I'll have a minimal demo up soon. It'll be my own private version running on my Raspberry Pi, just need to finish off some things before the initial release.
Also working on a small website with screenshots.

**Comment by sebastian-raubach** [comment]
Ok, so there's a website now: https://sebastian-raubach.github.io/frickl-web/
Wee demo to follow soon.

**Comment by sebastian-raubach** [comment]
I decided not to provide a demo for now, as I can't guarantee that my private copy is going to be available all the time. I'm also not sure my Pi and my internet connection could handle too much traffic. If I find a way to easily host this somewhere without any costs, I will.
